# Generated by Django 3.2.16 on 2022-12-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_name', to='webapp.room'),
        ),
    ]
