# Generated by Django 3.2.16 on 2022-12-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_booking_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
